name: Generate README

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '0 14 * * *'

jobs:
  generate-readme:
    name: Generate README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Generate README
        run: bun index.js > README.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          author_name: Popwers
          author_email: lionel.bataille@hotmail.com
          message: ':memo: README.md update'
