# This is a basic workflow to help you get started with Actions

name: README Update Bot

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '0 14 * * *'

jobs:
  # This workflow contains a single job called "build"
  generate-readme:
    name: Generate README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate
        run: echo Hello, world!
